ci: 🎡 disable snapshot tests
due to Swift error which apparently will be fixed with Xcode 13

diff --git a/.github/workflows/pr_only.yml b/.github/workflows/pr_only.yml
--- a/.github/workflows/pr_only.yml
+++ b/.github/workflows/pr_only.yml
@@ -55,49 +55,51 @@ jobs:
       - name: Verify formatted code is unchanged
         run: git diff --exit-code HEAD
 
-  SnapshotTests:
-    runs-on: macos-latest
-    env:
-      DEVELOPER_DIR: /Applications/Xcode_11.6.app/Contents/Developer
-    steps:
-    - name: Checkout Repo
-      uses: actions/checkout@v2
-    - name: Check for file changes in Sources folder
-      uses: getsentry/paths-filter@v2
-      id: changes
-      with:
-        filters: |
-          src:
-            - 'Sources/**'
-    - name: Checkout Snapshot references
-      uses: actions/checkout@v2
-      if: steps.changes.outputs.src == 'true'
-      with:
-        repository: SAP/cloud-sdk-ios-fiori-snapshot-references
-        path: Apps/Examples/cloud-sdk-ios-fiori-snapshot-references
-    - name: Generate Xcode project
-      if: steps.changes.outputs.src == 'true'
-      run: swift package generate-xcodeproj
-    - name: Install xcbeautify tool
-      if: steps.changes.outputs.src == 'true'
-      run:  |
-        brew tap thii/xcbeautify https://github.com/thii/xcbeautify.git
-        brew install xcbeautify
-    - name: Build Package
-      if: steps.changes.outputs.src == 'true'
-      run: set -o pipefail && xcodebuild -project FioriSwiftUI.xcodeproj -scheme FioriSwiftUI-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' build | xcbeautify
-    - name: Run snapshot tests
-      if: steps.changes.outputs.src == 'true'
-      run: set -o pipefail && xcodebuild -project ./Apps/Examples/Examples.xcodeproj -scheme ExamplesTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE (2nd generation)' test | xcbeautify
-    - name: Collect screenshot results on failure
-      if: failure()
-      run:  |
-        brew install chargepoint/xcparse/xcparse
-        ./scripts/snapshottesting/parseXcresult.sh
-    - name: Upload screenshot results on failure
-      if: failure()
-      uses: actions/upload-artifact@v1
-      with:
-        name: SnapshotTestResultImages
-        path: ./SnapshotTestResultImages
+## Disable SnapshotTests due to error: Unexpected duplicate tasks (https://bugs.swift.org/browse/SR-13739)
+## Renable SnapshotTests with Xcode 13 as Xcode 13 includes a fix
+#   SnapshotTests:
+#     runs-on: macos-latest
+#     env:
+#       DEVELOPER_DIR: /Applications/Xcode_11.6.app/Contents/Developer
+#     steps:
+#     - name: Checkout Repo
+#       uses: actions/checkout@v2
+#     - name: Check for file changes in Sources folder
+#       uses: getsentry/paths-filter@v2
+#       id: changes
+#       with:
+#         filters: |
+#           src:
+#             - 'Sources/**'
+#     - name: Checkout Snapshot references
+#       uses: actions/checkout@v2
+#       if: steps.changes.outputs.src == 'true'
+#       with:
+#         repository: SAP/cloud-sdk-ios-fiori-snapshot-references
+#         path: Apps/Examples/cloud-sdk-ios-fiori-snapshot-references
+#     - name: Generate Xcode project
+#       if: steps.changes.outputs.src == 'true'
+#       run: swift package generate-xcodeproj
+#     - name: Install xcbeautify tool
+#       if: steps.changes.outputs.src == 'true'
+#       run:  |
+#         brew tap thii/xcbeautify https://github.com/thii/xcbeautify.git
+#         brew install xcbeautify
+#     - name: Build Package
+#       if: steps.changes.outputs.src == 'true'
+#       run: set -o pipefail && xcodebuild -project FioriSwiftUI.xcodeproj -scheme FioriSwiftUI-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' build | xcbeautify
+#     - name: Run snapshot tests
+#       if: steps.changes.outputs.src == 'true'
+#       run: set -o pipefail && xcodebuild -project ./Apps/Examples/Examples.xcodeproj -scheme ExamplesTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE (2nd generation)' test | xcbeautify
+#     - name: Collect screenshot results on failure
+#       if: failure()
+#       run:  |
+#         brew install chargepoint/xcparse/xcparse
+#         ./scripts/snapshottesting/parseXcresult.sh
+#     - name: Upload screenshot results on failure
+#       if: failure()
+#       uses: actions/upload-artifact@v1
+#       with:
+#         name: SnapshotTestResultImages
+#         path: ./SnapshotTestResultImages
 
